export const defaultGamesData = [
  {
    "id": "racing-limits",
    "title": "Racing Limits",
    "description": "Connect blocks of numbers in high-octane speed challenges!",
    "iframeUrl": "https://racing-limits.game-files.crazygames.com/unity/unity2020/racing-limits.html?isFirstSession=true&v=2.2",
    "category": "Math Games",
    "icon": "Activity",
    "instructions": "Connect blocks of numbers in high-octane speed challenges!",
    "credits": "Math Playground Studio",
    "color": "from-orange-500 to-yellow-500",
    "thumbnailUrl": "https://i.ibb.co/FbVN4fYH/racing-limits-thumbnail-mathsplayground-copy.png",
    "thumbnailFit": "cover"
  },
  {
    "id": "city-bus-driver",
    "title": "City Bus Driver",
    "description": "Trace the paths with absolute concentration and guide your vehicle safely.",
    "iframeUrl": "https://games.crazygames.com/en_US/city-bus-driver/index.html?isFirstSession=true&v=2.2",
    "category": "Logic Lab",
    "icon": "Award",
    "instructions": "Hold and drag along the line carefully to guide the cat racer through winding curves.",
    "credits": "Nod Games",
    "color": "from-indigo-600 to-indigo-800",
    "thumbnailUrl": "https://i.ibb.co/cKFjgZHc/City-Bus-Driver-thumbnail.jpg",
    "thumbnailFit": "cover"
  },
  {
    "id": "drift-boss",
    "title": "Drift Boss Maze",
    "description": "Test your geometry and angles in this high-speed diagonal jumping puzzle.",
    "iframeUrl": "https://gamecollections.me/game/owner/drift-boss-gm/",
    "category": "Brain Boosts",
    "icon": "Compass",
    "instructions": "Tap and hold Space or Click to drift right. Double-jump at the blue checkpoints to pass obstacles.",
    "credits": "MarketJS",
    "color": "from-yellow-500 to-amber-600",
    "thumbnailUrl": "https://i.ibb.co/v6F16kT9/drift-boss-thumbnail-mathplaygroud-copy.webp",
    "thumbnailFit": "cover"
  },
  {
    "id": "subway-surfers",
    "title": "Subway Runner",
    "description": "Gather keys and shield block items in this mysterious underground dungeon run.",
    "iframeUrl": "https://szhong.4399.com/4399swf//upload_swf/ftp35/liuxinyu/20210324/jj01/index.html",
    "category": "Library",
    "icon": "Key",
    "instructions": "Dodge guards, slide under gates, collect the gold keys, and clear the dungeon block.",
    "credits": "SYBO Games",
    "color": "from-teal-500 to-cyan-600",
    "thumbnailUrl": "https://i.ibb.co/PG23ThWR/Subway-Surfersthumb-m240x144.jpg",
    "thumbnailFit": "cover"
  },
  {
    "id": "smash-karts",
    "title": "Math Karts",
    "description": "Guide your block karts to solve intense mechanical grid puzzle layouts.",
    "iframeUrl": "https://smashkarts.io",
    "category": "Library",
    "icon": "Gamepad",
    "instructions": "Rotate switches, align lock blocks, and guide your kart to trigger the green gate portals.",
    "credits": "Tall Team",
    "color": "from-rose-500 to-red-650",
    "thumbnailUrl": "https://i.ibb.co/qLydHLys/smashkarts-thumb-2.png",
    "thumbnailFit": "cover"
  },
  {
    "id": "gulper-io",
    "title": "Gulper.io",
    "description": "Launch your logic forward in Use Your Head Part 3, testing gravity, speed, and timing.",
    "iframeUrl": "https://gulper.io/?isNewUser=false&__nextLocale=en-US",
    "category": "Brain Boosts",
    "icon": "Sliders",
    "instructions": "Propel the elastic block head to hit the target button. Control velocity and wall rebounds.",
    "credits": "Head Labs",
    "color": "from-pink-500 to-rose-650",
    "thumbnailUrl": "https://i.ibb.co/wZPHvNSB/Gulper-io-thumbnail.png",
    "thumbnailFit": "cover"
  },
  {
    "id": "rodha",
    "title": "Rodha bounce",
    "description": "Classic Rodha platformer where you hop across triggers, spikes, and rotating lines.",
    "iframeUrl": "https://www.crazygames.com/embed/rodha",
    "category": "Math Games",
    "icon": "Target",
    "instructions": "Press A/D or Left/Right Arrow keys to jump side to side. Avoid dangerous gears, triggers, and spiked wheels.",
    "credits": "Sebastian",
    "color": "from-blue-600 to-blue-800",
    "thumbnailUrl": "https://i.ibb.co/Hp9R3mL4/Rodha-thumbnail.png",
    "thumbnailFit": "cover"
  },
  {
    "id": "plonky",
    "title": "Plonky Escape",
    "description": "Help the bouncing ball jump and slide to reach the security goal in Glitch.",
    "iframeUrl": "https://g.igroutka.ru/games/1278/hMRVJrwIQ8mYf6AS/d4d99b3a-cc26-41af-98df-da4c196e5308/index.html",
    "category": "Logic Lab",
    "icon": "Cpu",
    "instructions": "Bounce through static spikes, slide down moving walls, and time your jump perfectly.",
    "credits": "GameTornado",
    "color": "from-emerald-500 to-teal-600",
    "thumbnailUrl": "https://i.ibb.co/Lz5Jm5L2/Plonky-Thumbnail.jpg",
    "thumbnailFit": "cover"
  },
  {
    "id": "stickman-hook",
    "title": "Stickman Hook",
    "description": "Control the swinging, bouncy ball and fly over platforms in Rodha Bounce.",
    "iframeUrl": "https://stickhook.io/game/stickman-hook/",
    "category": "Logic Lab",
    "icon": "Activity",
    "instructions": "Tap left/right arrow buttons to swing and roll. Launch high off bounce pads to reach the flags.",
    "credits": "Madbox",
    "color": "from-purple-500 to-indigo-600",
    "thumbnailUrl": "https://i.ibb.co/1f3fmdDY/Stickman-Hook.png",
    "thumbnailFit": "cover"
  },
  {
    "id": "moto-x3m-2",
    "title": "Moto X3M 2",
    "description": "Guide duck life runners across elevated logic panels and obstacles.",
    "iframeUrl": "https://html5.gamedistribution.com/rvvASMiM/5b0abd4c0faa4f5eb190a9a16d5a1b4c/index.html?gd_zone_config=eyJwYXJlbnRVUkwiOiJodHRwczovL21vdG94M20yLmlvLyIsInBhcmVudERvbWFpbiI6Im1vdG94M20yLmlvIiwidG9wRG9tYWluIjoibW90b3gzbTIuaW8iLCJoYXNJbXByZXNzaW9uIjpmYWxzZSwibG9hZGVyRW5hYmxlZCI6dHJ1ZSwiaG9zdCI6Imh0bWw1LmdhbWVkaXN0cmlidXRpb24uY29tIiwidmVyc2lvbiI6IjEuNS4xOCJ9",
    "category": "Brain Boosts",
    "icon": "Zap",
    "instructions": "Steer and lean the motorcycle racer precisely over loops and ramps inside the logic course.",
    "credits": "Madpuffers",
    "color": "from-red-500 to-orange-600",
    "thumbnailUrl": "https://i.ibb.co/Mx3tBk87/Moto-x3m-thumbnail-mathsplayground-copy.avif",
    "thumbnailFit": "cover"
  },
  {
    "id": "blacktop-police-chase",
    "title": "Police Chase",
    "description": "Slide and feed the purple math monster to clear numbers in Monsterland.",
    "iframeUrl": "https://g.igroutka.ru/games/1108/QZXcUlJgwk2m9rxn/d8e221af-370e-451f-9f45-a747831936e4/index.html",
    "category": "Library",
    "icon": "AlertTriangle",
    "instructions": "Maneuver, collect coins, and solve quick subtraction blocks before time runs empty.",
    "credits": "Steelpan Games",
    "color": "from-amber-600 to-red-650",
    "thumbnailUrl": "https://i.ibb.co/NdjcsKN0/blacktop-police-chase-thumbnail-mathplayground-copy.jpg",
    "thumbnailFit": "cover"
  },
  {
    "id": "bomb-hopper",
    "title": "BombHopper Space",
    "description": "Bounce and solve cheese path logic problems with agile ninja hamsters.",
    "iframeUrl": "https://bombhopper.io/",
    "category": "Library",
    "icon": "Bomb",
    "instructions": "Launch explosive cookies or cheese blocks to throw the hamster into the portal.",
    "credits": "BombHopper Team",
    "color": "from-indigo-500 to-pink-500",
    "thumbnailUrl": "https://i.ibb.co/Ldj8bBjh/Bomb-hopper-io-Thumbnail.webp",
    "thumbnailFit": "cover"
  },
  {
    "id": "arcade-glide",
    "title": "Arcade Drift",
    "description": "Race through endless drifting tracks, unlock stylish cars, master sharp turns, and chase high scores.",
    "iframeUrl": "https://geometry-games.io/embed/arcade-glide?pub_id=ca-pub-8859934936389708&preroll=1&preroll_type=adsense",
    "category": "Brain Boosts",
    "icon": "Compass",
    "instructions": "Press Left/Right Arrow keys or A/D to steer and drift. Hold or press Space to customize drifts on sharp turns.",
    "credits": "Geometry Games",
    "color": "from-pink-500 to-indigo-600",
    "thumbnailUrl": "https://i.ibb.co/6q1tt3C/arcade-glidde-thumbnail-mathplayground-copy.jpg",
    "thumbnailFit": "cover"
  },
  {
    "id": "drive-mad",
    "title": "Drive Mad",
    "description": "Steer a high-powered 4x4 stunt truck over thrilling, mind-bending interactive physical tracks.",
    "iframeUrl": "https://gamecollections.me/game/3kh0-assets-main/drive-mad/",
    "category": "Brain Boosts",
    "icon": "Zap",
    "instructions": "Use Left/Right or A/D keys to accelerate and reverse. Coordinate precise speed bursts to master leaps and balance over hurdles.",
    "credits": "Martin Magni",
    "color": "from-yellow-400 to-amber-500",
    "thumbnailUrl": "https://i.ibb.co/35sDzK5n/drive-mad-thumbnail-mathsplayground-copy.webp",
    "thumbnailFit": "cover"
  },
  {
    "id": "basket-random",
    "title": "Basket Random",
    "description": "Experience wacky 2-player basketball physics. Bounce, bobble, and slam-dunk your way to victory!",
    "iframeUrl": "https://html5.gamedistribution.com/bf1268dccb5d43e7970bb3edaa54afc8/?gd_sdk_referrer_url=https://basketrandom.io/basket-random",
    "category": "Brain Boosts",
    "icon": "Gamepad",
    "instructions": "Press Up Arrow key or click to jump, bounce, and throw. First to score 5 points wins!",
    "credits": "RHM Interactive",
    "color": "from-amber-500 to-orange-600",
    "thumbnailUrl": "https://img.gamedistribution.com/bf1268dccb5d43e7970bb3edaa54afc8-512x512.jpeg",
    "thumbnailFit": "cover"
  },
  {
    "id": "vex-7",
    "title": "Vex 7",
    "description": "Perform spectacular acrobatic parkour leaps and navigate hazardous traps in this high-intensity stickman platformer.",
    "iframeUrl": "https://www.coolmathgames.com/sites/default/files/public_games/43835/?gd_sdk_referrer_url=https%3A%2F%2Fwww.coolmathgames.com%2F0-vex-7",
    "category": "Brain Boosts",
    "icon": "Zap",
    "instructions": "Move with WASD or Arrow Keys. Jump with W or Up Arrow, slide or crouch with S or Down Arrow. Scale walls, leap over spikes, and reach the green portal safely.",
    "credits": "Amazing Adam",
    "color": "from-orange-500 to-amber-600",
    "thumbnailUrl": "https://i.ibb.co/TJz0RTd/Vex-7-thumbnail-mp.jpg",
    "thumbnailFit": "cover"
  },
  {
    "id": "escape-road-2",
    "title": "Escape Road 2",
    "description": "Escape the law! Maneuver your getaway car, pull drift tricks, avoid blockades, and survive the chase.",
    "iframeUrl": "https://game.azgame.io/escape-road-2/",
    "category": "Logic Lab",
    "icon": "Compass",
    "instructions": "Use WASD or Arrow Keys to steer and navigate. Keep away from pursuing police cruisers and dodge obstacles.",
    "credits": "AZ Games",
    "color": "from-red-600 to-amber-700",
    "thumbnailUrl": "https://i.ibb.co/YwCyHxH/Escape-Road-thumbnail-mp.png",
    "thumbnailFit": "cover"
  }
];
